### ISSUE TITLE
Demo: 

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#1345]
## Description

Next demo not working with the latest released packages.

### Steps to reproduce

```
cd packages/demo-next
yarn dev
```

### Expected result

http://localhost:3000 displays fine.

### Actual result

http://localhost:3000 display error:

```
document is not defined

ReferenceError: document is not defined
    at e.Dismissible (/Users/frank/tina/tinacms/node_modules/react-dismissible/build/index.js:1:1014)
    at processChild (/Users/frank/tina/tinacms/node_modules/react-dom/cjs/react-dom-server.node.development.js:3204:14)
    at resolve (/Users/frank/tina/tinacms/node_modules/react-dom/cjs/react-dom-server.node.development.js:3124:5)
    at ReactDOMServerRenderer.render (/Users/frank/tina/tinacms/node_modules/react-dom/cjs/react-dom-server.node.development.js:3598:22)
    at ReactDOMServerRenderer.read (/Users/frank/tina/tinacms/node_modules/react-dom/cjs/react-dom-server.node.development.js:3536:29)
    at renderToString (/Users/frank/tina/tinacms/node_modules/react-dom/cjs/react-dom-server.node.development.js:4245:27)
    at render (/Users/frank/tina/tinacms/node_modules/next/dist/next-server/server/render.js:80:16)
    at Object.renderPage (/Users/frank/tina/tinacms/node_modules/next/dist/next-server/server/render.js:291:16)
    at /Users/frank/tina/tinacms/packages/demo-next/.next/server/static/development/pages/_document.js:4360:21
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/frank/tina/tinacms/packages/demo-next/.next/server/static/development/pages/_document.js:239:24)
    at _next (/Users/frank/tina/tinacms/packages/demo-next/.next/server/static/development/pages/_document.js:261:9)
    at /Users/frank/tina/tinacms/packages/demo-next/.next/server/static/development/pages/_document.js:268:7
    at new Promise (<anonymous>)
    at new F (/Users/frank/tina/tinacms/packages/demo-next/.next/server/static/development/pages/_document.js:1391:28)
    at /Users/frank/tina/tinacms/packages/demo-next/.next/server/static/development/pages/_document.js:257:12
```

#### Tinacms Package Versions

```text
├── UNMET DEPENDENCY @tinacms/api-git@0.5.3
├── UNMET DEPENDENCY @tinacms/form-builder@^0.24.0
├── UNMET DEPENDENCY @tinacms/git-client@0.4.1
├── UNMET DEPENDENCY @tinacms/styles@^0.24.0
├── UNMET DEPENDENCY next-tinacms-json@0.1.2
├── UNMET DEPENDENCY next-tinacms-markdown@0.1.0-canary.2441
├── UNMET DEPENDENCY react-tinacms-editor@^0.24.1-alpha.0
├── UNMET DEPENDENCY react-tinacms-inline@^0.24.0
├── UNMET DEPENDENCY tinacms@^0.24.0
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser | Firefox    |
| os      |  macOS 10.15.5    |
| node    |   12.6.1      |
| yarn      | 1.22.4  |

**Comment by DirtyF** [comment]
Nevermind, after rebuilding all packages locally, the demo works fine.
