### ISSUE TITLE
failing test: deleteEmpttyHeading should delete an empty heading

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#139]
This test is currently failing, even though the function works.

**Output**

```
* deleteEmptyHeading › should delete an empty heading

    RangeError: Selection passed to setSelection must point at the current document

      19 |         )
      20 |         // Set the seleciton to be at the start of the paragram
    > 21 |         .setSelection(Selection.near(state.doc.resolve($cursor.pos - 1)))
         |          ^
      22 |     )
      23 |   }
      24 |   return true

      at Transaction.setSelection (../../../node_modules/prosemirror-state/src/transaction.js:62:13)
      at deleteEmptyHeading (src/Wysiwyg/commands/heading-commands.ts:21:10)
      at PMTestHarness.apply (src/prosemirror-test-utils/index.ts:68:12)
      at Object.<anonymous> (src/Wysiwyg/commands/heading-commands.test.ts:16:8)
```

**Comment by jpuri** [comment]
This issue appears to be fixed already in latest code.
