### ISSUE TITLE
yarn tina-dev fails (events.js:352  throw er; // Unhandled 'error' event)

### ISSUE THREAD

**Issue by perkinsjr** [tinacms/tinacms#1951]
## Description

Testing on a windows 10 machine after using `@tinacms/cli init` on a freshly bootstrapped next.js application. As soon as you attempt to launch using tina-dev the app fails to launch after types are generated.

### Steps to reproduce

1. bootstrap a Next site `npx create-next-app tina-test`
2. init tina `npx @tincms/cli init` 
3. run `yarn tina-dev`
4. Error is returned 
### Expected result

Application should launch successfully

What should happen?

### Actual result

Types get generated by application crashed with the following error:

```bash
$ yarn tinacms server:start -c "next dev"
$ C:\development\tina-test\node_modules\.bin\tinacms server:start -c "next dev"

Started Filesystem GraphQL server on port: 4001
Visit the playground at http://localhost:4001/altair/
Generating Tina config
Compiling...
Transpiling...
Generating types...
Typescript types => C:\development\tina-test/.tina/__generated__/types.ts
GraphQL types ====> C:\development\tina-test/.tina/__generated__/schema.gql
events.js:352
      throw er; // Unhandled 'error' event
      ^

Error: spawn next ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn next',
  path: 'next',
  spawnargs: [ 'dev' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment

Windows 10
Node 14.7
npm 6.14.13

#### Tinacms Package Versions

```text
+-- @tinacms/cli@0.51.1
| +-- @tinacms/graphql@0.50.2
`-- tinacms@0.50.1
  +-- @tinacms/toolkit@0.50.0

```

**Comment by mitchmac** [comment]
@perkinsjr -- can you take a pass through this one again -- looks like it's fixed? (may need a release if the fix isn't present)

**Comment by perkinsjr** [comment]
@mitchmac I will test todo and let you know what I find out.

**Comment by perkinsjr** [comment]
Confirmed this is now fixed. Tested on windows 10 using git bash and command prompt with zero issues.
