### ISSUE TITLE
Image field needs a placeholder for broken images

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#203]
When an image field's src is set to "", it doesn't render a placeholder. This makes it difficult to upload an image, as the clickable dropzone area is very small.
<img width="343" alt="Screen Shot 2019-10-02 at 9 32 02 AM" src="https://user-images.githubusercontent.com/3323181/66044413-de59e880-e4f7-11e9-808e-22c1c8c0075a.png">

**Comment by maribelduran** [comment]
I'm working on a fix for this :) Will submit PR

**Comment by ncphillips** [comment]
Hey @maribelduran! Did you have any luck?

**Comment by ovpv** [comment]
can I try this?

**Comment by ovpv** [comment]
@ncphillips  Please help. I am getting the following error while running the script `npm run dev`

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/ovpv/.nvm/versions/node/v12.9.1/bin/node',
1 verbose cli   '/Users/ovpv/.nvm/versions/node/v12.9.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.10.2
3 info using node@v12.9.1
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @tinacms/api-git@0.2.4~predev: @tinacms/api-git@0.2.4
6 info lifecycle @tinacms/api-git@0.2.4~dev: @tinacms/api-git@0.2.4
7 verbose lifecycle @tinacms/api-git@0.2.4~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @tinacms/api-git@0.2.4~dev: PATH: /Users/ovpv/.nvm/versions/node/v12.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ovpv/Desktop/OneDrive-ovpv.com/vishnu-projects/opensource/tinacms/packages/@tinacms/api-git/node_modules/.bin:/Users/ovpv/Desktop/OneDrive-ovpv.com/vishnu-projects/opensource/tinacms/packages/@tinacms/api-git/node_modules/.bin:/Users/ovpv/Desktop/OneDrive-ovpv.com/vishnu-projects/opensource/tinacms/packages/@tinacms/node_modules/.bin:/Users/ovpv/Desktop/OneDrive-ovpv.com/vishnu-projects/opensource/tinacms/packages/node_modules/.bin:/Users/ovpv/Desktop/OneDrive-ovpv.com/vishnu-projects/opensource/tinacms/node_modules/.bin:/Users/ovpv/Desktop/OneDrive-ovpv.com/vishnu-projects/opensource/node_modules/.bin:/Users/ovpv/Desktop/OneDrive-ovpv.com/vishnu-projects/node_modules/.bin:/Users/ovpv/Desktop/OneDrive-ovpv.com/node_modules/.bin:/Users/ovpv/Desktop/node_modules/.bin:/Users/ovpv/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/Users/ovpv/.nvm/versions/node/v12.9.1/bin:/Users/ovpv/.nvm/versions/node/v12.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ovpv/Desktop/OneDrive-ovpv.com/vishnu-projects/opensource/tinacms/node_modules/.bin:/Users/ovpv/Library/Android/sdk/platform-tools:/Users/ovpv/Library/Android/sdk/tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Apple/bin:/Users/ovpv/Library/Android/sdk/platform-tools:/Users/ovpv/Library/Android/sdk/tools:/Users/ovpv/.sdkman/candidates/gradle/current/bin:/Users/ovpv/.nvm/versions/node/v12.9.1/bin
9 verbose lifecycle @tinacms/api-git@0.2.4~dev: CWD: /Users/ovpv/Desktop/OneDrive-ovpv.com/vishnu-projects/opensource/tinacms/packages/@tinacms/api-git
10 silly lifecycle @tinacms/api-git@0.2.4~dev: Args: [ '-c', 'tinacms-scripts dev' ]
11 info lifecycle @tinacms/api-git@0.2.4~dev: Failed to exec dev script
12 verbose stack Error: @tinacms/api-git@0.2.4 dev: `tinacms-scripts dev`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/Users/ovpv/.nvm/versions/node/v12.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:209:13)
12 verbose stack     at maybeClose (internal/child_process.js:1021:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
13 verbose pkgid @tinacms/api-git@0.2.4
14 verbose cwd /Users/ovpv/Desktop/OneDrive-ovpv.com/vishnu-projects/opensource/tinacms/packages/@tinacms/api-git
15 verbose Darwin 19.0.0
16 verbose argv "/Users/ovpv/.nvm/versions/node/v12.9.1/bin/node" "/Users/ovpv/.nvm/versions/node/v12.9.1/bin/npm" "run" "dev"
17 verbose node v12.9.1
18 verbose npm  v6.10.2
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error @tinacms/api-git@0.2.4 dev: `tinacms-scripts dev`
23 error spawn ENOENT
24 error Failed at the @tinacms/api-git@0.2.4 dev script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by jamespohalloran** [comment]
Hey @ovpv, have you run `npm run bs` first? Just tried:
```
npm run bs
npm run dev
``` on master and it's building correctly for me.

Also if that doesn't work, is `npm run build` working for you?

**Comment by maribelduran** [comment]
@ncphillips started research on it, but haven't had time to continue :(  @ovpv please go ahead! I'll unassign myself from this for now and take another issue that I was hoping to work on too

**Comment by ovpv** [comment]
Hey @ncphillips @jamespohalloran 

I tried following the contribution [docs](https://github.com/tinacms/tinacms/blob/master/CONTRIBUTING.md#How-to-Contribute), but it seems incomplete. How do I start the dev environment to fix this issue?

For now, I have cloned the tina-starter project,  as instructed [here](https://tinacms.org/docs/gatsby/quickstart) and identified the issue mentioned (File: ImageUpload.tsx L: 105) but I don't know the proper procedure to implement the fix in core project and test it. So please guide me through the steps forward

**Comment by ovpv** [comment]
@ncphillips 

Still unable to run the dev server. Getting this error. Please help.

```
ERROR #10226  CONFIG

Couldn't find the "gatsby-plugin-tinacms" plugin declared in "/Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/vishnu-projects/opensource/tinacms/packages/demo-gatsby/gatsby-config.js".

Tried looking for a local plugin in /Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/vishnu-projects/opensource/tinacms/packages/demo-gatsby/plugins/gatsby-plugin-tinacms.

Tried looking for an installed package in the following paths:
 - /Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/vishnu-projects/opensource/tinacms/node_modules/gatsby/dist/bootstrap/load-themes/node_modules/gatsby-plugin-tinacms
 - /Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/vishnu-projects/opensource/tinacms/node_modules/gatsby/dist/bootstrap/node_modules/gatsby-plugin-tinacms
 - /Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/vishnu-projects/opensource/tinacms/node_modules/gatsby/dist/node_modules/gatsby-plugin-tinacms
 - /Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/vishnu-projects/opensource/tinacms/node_modules/gatsby/node_modules/gatsby-plugin-tinacms
 - /Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/vishnu-projects/opensource/tinacms/node_modules/gatsby-plugin-tinacms
 - /Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/vishnu-projects/opensource/node_modules/gatsby-plugin-tinacms
 - /Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/vishnu-projects/node_modules/gatsby-plugin-tinacms
 - /Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/node_modules/gatsby-plugin-tinacms
 - /Users/wisdmlabs/Desktop/node_modules/gatsby-plugin-tinacms
 - /Users/wisdmlabs/node_modules/gatsby-plugin-tinacms
 - /Users/node_modules/gatsby-plugin-tinacms
 - /node_modules/gatsby-plugin-tinacms

not finished open and validate gatsby-configs - 0.061s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! demo-gatsby@1.1.0 develop: `gatsby develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the demo-gatsby@1.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wisdmlabs/.npm/_logs/2019-11-05T12_14_24_261Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! demo-gatsby@1.1.0 start: `npm run develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the demo-gatsby@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wisdmlabs/.npm/_logs/2019-11-05T12_14_24_303Z-debug.log
```

**Comment by ovpv** [comment]
@ncphillips , dev server is not working. Getting the following error, please help 

```
> demo-gatsby@1.1.0 develop /Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/vishnu-projects/opensource/tinacms/packages/demo-gatsby
> gatsby develop


 ERROR #10226  CONFIG

Couldn't find the "gatsby-plugin-tinacms" plugin declared in "/Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/vishnu-projects/opensource/tinacms/packages/demo-gatsby/gatsby-config.js".

Tried looking for a local plugin in /Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/vishnu-projects/opensource/tinacms/packages/demo-gatsby/plugins/gatsby-plugin-tinacms.

Tried looking for an installed package in the following paths:
 - /Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/vishnu-projects/opensource/tinacms/node_modules/gatsby/dist/bootstrap/load-themes/node_modules/gatsby-plugin-tinacms
 - /Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/vishnu-projects/opensource/tinacms/node_modules/gatsby/dist/bootstrap/node_modules/gatsby-plugin-tinacms
 - /Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/vishnu-projects/opensource/tinacms/node_modules/gatsby/dist/node_modules/gatsby-plugin-tinacms
 - /Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/vishnu-projects/opensource/tinacms/node_modules/gatsby/node_modules/gatsby-plugin-tinacms
 - /Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/vishnu-projects/opensource/tinacms/node_modules/gatsby-plugin-tinacms
 - /Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/vishnu-projects/opensource/node_modules/gatsby-plugin-tinacms
 - /Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/vishnu-projects/node_modules/gatsby-plugin-tinacms
 - /Users/wisdmlabs/Desktop/OneDrive-Wisdmlabs.com/node_modules/gatsby-plugin-tinacms
 - /Users/wisdmlabs/Desktop/node_modules/gatsby-plugin-tinacms
 - /Users/wisdmlabs/node_modules/gatsby-plugin-tinacms
 - /Users/node_modules/gatsby-plugin-tinacms
 - /node_modules/gatsby-plugin-tinacms

not finished open and validate gatsby-configs - 0.040s

lerna ERR! npm run develop stderr:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! demo-gatsby@1.1.0 develop: `gatsby develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the demo-gatsby@1.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wisdmlabs/.npm/_logs/2019-11-05T13_02_07_534Z-debug.log

lerna ERR! npm run develop exited 1 in 'demo-gatsby'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
```

**Comment by ncphillips** [comment]
It looks to me like the `gatsby-plugin-tinacms` wasn't built. Try running `npm run build`

As an aside, troubles with development are not related to this issue. Could you either open a [new development issue](https://github.com/tinacms/tinacms/issues/new?labels=development&template=development.md) or post a message in the [Tina Slack](https://tinacms.org/community/)?

**Comment by weibenfalk** [comment]
Created a PR for this one with my suggested solution.
