### ISSUE TITLE
Unable to start local server when using `--experimentalData`

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#2517]
Run 
```bash
yarn tinacms server:start
```
(everything works as expected)

Run
```bash
yarn tinacms server:start --experimentalData
```

get the following error

```
$ /Users/logananderson-forestry-mac/dev/personal/blog-nextjs-tina-tailwind/node_modules/.bin/tinacms server:start --experimentalData

Started Filesystem GraphQL server on port: 4001
Visit the playground at http://localhost:4001/altair/
Generating Tina config
Compiling...
Transpiling...

/Users/logananderson-forestry-mac/dev/personal/blog-nextjs-tina-tailwind/node_modules/levelup/lib/levelup.js:127
      return callback(new OpenError(err))
                      ^
Error [OpenError]: IO error: lock /Users/logananderson-forestry-mac/dev/personal/blog-nextjs-tina-tailwind/.tina/__generated__/db/LOCK: already held by process
    at /Users/logananderson-forestry-mac/dev/personal/blog-nextjs-tina-tailwind/node_modules/levelup/lib/levelup.js:127:23
    at /Users/logananderson-forestry-mac/dev/personal/blog-nextjs-tina-tailwind/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    at onopen (/Users/logananderson-forestry-mac/dev/personal/blog-nextjs-tina-tailwind/node_modules/deferred-leveldown/deferred-leveldown.js:49:14)
    at /Users/logananderson-forestry-mac/dev/personal/blog-nextjs-tina-tailwind/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    at /Users/logananderson-forestry-mac/dev/personal/blog-nextjs-tina-tailwind/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
Emitted 'error' event on LevelUP instance at:
    at /Users/logananderson-forestry-mac/dev/personal/blog-nextjs-tina-tailwind/node_modules/levelup/lib/levelup.js:56:19
    at /Users/logananderson-forestry-mac/dev/personal/blog-nextjs-tina-tailwind/node_modules/levelup/lib/levelup.js:127:14
    at /Users/logananderson-forestry-mac/dev/personal/blog-nextjs-tina-tailwind/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    [... lines matching original stack trace ...]
    at /Users/logananderson-forestry-mac/dev/personal/blog-nextjs-tina-tailwind/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Video: https://www.loom.com/share/98b4d460cdc74845a789cd89544d7d83

I am using VS code.

## **Update: ** 

I updated the packages to `"@tinacms/cli": "^0.60.2",` ( was on "@tinacms/cli": "^0.60.0",). Now I am getting a different error after the output hangs here for a while (about one min)

```
yarn run v1.22.17
$ /Users/logananderson-forestry-mac/dev/personal/blog-nextjs-tina-tailwind/node_modules/.bin/tinacms server:start --experimentalData

Started Filesystem GraphQL server on port: 4001
Visit the playground at http://localhost:4001/altair/
Generating Tina config
Compiling...
Transpiling...
```

and then after a while it crashes with this error message.
```
yarn run v1.22.17
$ /Users/logananderson-forestry-mac/dev/personal/blog-nextjs-tina-tailwind/node_modules/.bin/tinacms server:start --experimentalData

Started Filesystem GraphQL server on port: 4001
Visit the playground at http://localhost:4001/altair/
Generating Tina config
Compiling...
Transpiling...

<--- Last few GCs --->

[9029:0x104a0a000]    75104 ms: Mark-sweep (reduce) 4093.1 (4100.8) -> 4092.1 (4102.0) MB, 5838.5 / 0.0 ms  (+ 1.6 ms in 2490 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 6737 ms) (average mu = 0.197, current mu = 0.1[9029:0x104a0a000]    81316 ms: Mark-sweep (reduce) 4093.1 (4101.0) -> 4092.3 (4102.0) MB, 6210.6 / 0.0 ms  (average mu = 0.105, current mu = 0.000) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10130d6e5 node::Abort() (.cold.1) [/Users/logananderson-forestry-mac/.nvm/versions/node/v14.17.0/bin/node]
 2: 0x1000b1c49 node::Abort() [/Users/logananderson-forestry-mac/.nvm/versions/node/v14.17.0/bin/node]
 3: 0x1000b1daf node::OnFatalError(char const*, char const*) [/Users/logananderson-forestry-mac/.nvm/versions/node/v14.17.0/bin/node]
 4: 0x1001f60f7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/logananderson-forestry-mac/.nvm/versions/node/v14.17.0/bin/node]
 5: 0x1001f6093 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/logananderson-forestry-mac/.nvm/versions/node/v14.17.0/bin/node]
 6: 0x1003a54f5 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/logananderson-forestry-mac/.nvm/versions/node/v14.17.0/bin/node]
 7: 0x1003a6fba v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/Users/logananderson-forestry-mac/.nvm/versions/node/v14.17.0/bin/node]
 8: 0x1003a2689 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/logananderson-forestry-mac/.nvm/versions/node/v14.17.0/bin/node]
 9: 0x10039ff21 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/logananderson-forestry-mac/.nvm/versions/node/v14.17.0/bin/node]
10: 0x1003ae7da v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/logananderson-forestry-mac/.nvm/versions/node/v14.17.0/bin/node]
11: 0x1003ae861 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/logananderson-forestry-mac/.nvm/versions/node/v14.17.0/bin/node]
12: 0x10037bf12 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Users/logananderson-forestry-mac/.nvm/versions/node/v14.17.0/bin/node]
13: 0x1006fc158 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/logananderson-forestry-mac/.nvm/versions/node/v14.17.0/bin/node]
14: 0x100a893d9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/logananderson-forestry-mac/.nvm/versions/node/v14.17.0/bin/node]
15: 0x100a4ec07 Builtins_AsyncFunctionAwaitUncaught [/Users/logananderson-forestry-mac/.nvm/versions/node/v14.17.0/bin/node]
16: 0x1be73530a86f 
17: 0x100a222a2 Builtins_InterpreterEntryTrampoline [/Users/logananderson-forestry-mac/.nvm/versions/node/v14.17.0/bin/node]
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

cc @jeffsee55 and @kldavis4

**Comment by jamespohalloran** [comment]
@logan-anderson Is this working for you now?
