### ISSUE TITLE
Typescript Bug – TS2742: The inferred type of 'ModalHeader' cannot be named without a reference to ...

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#277]
```
lerna notice cli v3.16.4
lerna info versioning independent
lerna info filter [ '@tinacms/tinacms' ]
lerna info Executing command in 1 package: "npm run build"
lerna ERR! npm run build exited 1 in '@tinacms/tinacms'
lerna ERR! npm run build stdout:

> @tinacms/tinacms@0.2.0-alpha.0 build /Users/ncphillips/Code/tinacms/tinacms/packages/tinacms
> cms-scripts build

Building Package: @tinacms/tinacms@0.2.0-alpha.0

lerna ERR! npm run build stderr:
/Users/ncphillips/Code/tinacms/tinacms/packages/@tinacms/scripts/bin/cms-scripts.js:33
  throw err
  ^

Error: /Users/ncphillips/Code/tinacms/tinacms/packages/tinacms/src/components/modals/ModalProvider.tsx(113,14): semantic error TS2742: The inferred type of 'ModalHeader' cannot be named without a reference to '@tinacms/fields/node_modules/@tinacms/styles'. This is likely not portable. A type annotation is necessary.
    at error (/Users/ncphillips/Code/tinacms/tinacms/node_modules/rollup/dist/rollup.js:10151:30)
    at throwPluginError (/Users/ncphillips/Code/tinacms/tinacms/node_modules/rollup/dist/rollup.js:16454:12)
    at Object.error (/Users/ncphillips/Code/tinacms/tinacms/node_modules/rollup/dist/rollup.js:16509:24)
    at Object.error (/Users/ncphillips/Code/tinacms/tinacms/node_modules/rollup/dist/rollup.js:16901:38)
    at RollupContext.error (/Users/ncphillips/Code/tinacms/tinacms/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17192:30)
    at lodash_3 (/Users/ncphillips/Code/tinacms/tinacms/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24953:23)
    at arrayEach (/Users/ncphillips/Code/tinacms/tinacms/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:532:11)
    at forEach (/Users/ncphillips/Code/tinacms/tinacms/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9358:14)
    at printDiagnostics (/Users/ncphillips/Code/tinacms/tinacms/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24926:5)
    at cache.getCompiled (/Users/ncphillips/Code/tinacms/tinacms/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:26820:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tinacms/tinacms@0.2.0-alpha.0 build: `cms-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tinacms/tinacms@0.2.0-alpha.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ncphillips/.npm/_logs/2019-10-09T19_02_43_357Z-debug.log
```

Related Issue:
* https://github.com/Microsoft/TypeScript/issues/30858

Putting this in a bunch of files fixes the issue:

<img width="578" alt="image" src="https://user-images.githubusercontent.com/824015/66517651-e0a0e180-eab9-11e9-8e55-fc9265c33fc8.png">

Which makes no sense because that file doesn't reference `@tinacms/fields`

**Comment by ncphillips** [comment]
This seems to have resolved itself 🤷‍♂ 

I'm leaving this open anyway
