### ISSUE TITLE
Upgrading past v0.66.9 breaks collections with multiple templates (and causes other small bugs)

### ISSUE THREAD

**Issue by coreyaus** [tinacms/tinacms#2817]
## Description

Hey legends - I have a project using `tinacms@0.66.9` and I see the following series of issues appear when upgrading to version `0.66.10` or version `0.67.0`:

1. Collections break if they implement multiple different templates (i.e. passing an array of `templates` rather than an array of `fields`). The error message in the Tina Admin view when trying to create or edit a document in that collection is:
    > Failed to assertShape - _template is a required field
    - You can also see that in the screenshot below
    - That persists even when settings `cms.flags.set('use-unstable-formify', false)`

2. The issue described here: #2816

3. The `TinaCollection`/`TinaCloudCollection` types seem to break
    - That is, a TypeScript error appears in `schema.ts` when running code like the following:
        ```typescript
        import pagesCollection from './schema/collections/pages'
        
        export default defineSchema({
            collections: [pagesCollection],
        })
        ```
    - The TS error appears on the `collections: [pagesCollection]` line. It claims that the types expected for that `collections` property are not compatible with the `TinaCollection` or `TinaCloudCollection` types used in the `pagesCollection` file, which are:
        ```typescript
        import type { TinaCollection, TinaCloudCollection } from '@tinacms/cli'
        const pagesCollection: TinaCollection | TinaCloudCollection = {
            label: 'Pages',
            name: 'pages',
            path: 'content/pages',
            fields: [...],
        }
        export default pagesCollection
        ```
    - Please let me know if there is something wrong with those types I'm using - they work fine when running `tinacms@0.66.9`

4. The Tina hamburger menu to open the list of collections, media manager, etc. stops working, unless we set `reactStrictMode: false` in our `next.config.js` file

Please let me know if you have any questions about those points or need more info. Thanks for all your efforts building such a sensational tool! 🙌 

### Steps to reproduce

I have a private repository that currently works on `v0.66.9` and all these issues are visible when upgrading. I'd be happy to share access to that repository with the relevant people from the Tina core team. Alternatively, I'm happy to run tests myself with a patch version of tinacms if you have an idea for these fixes and want me to review whether an updated/edge version resolves the issues above 👍 

### Expected result vs actual result

I expect to be able to upgrade without the errors listed above but currently we need to run tinacms 2 versions behind the latest in order to avoid those issues

#### Tinacms Package Versions

These are the versions where everything works. The issues outlined above emerge when I upgrade to `tinacms@0.66.10` or `tinacms@0.67.0`

```text
├── @tinacms/auth@0.50.2
├── @tinacms/cli@0.60.11
├── next-tinacms-cloudinary@3.5.13
├── tinacms@0.66.9
```

![tinacms-render-error-collection-with-templates](https://user-images.githubusercontent.com/7799612/163698522-2ae76510-6989-4199-b558-9b618a3a770a.png)

**Comment by cjmcintyre** [comment]
If it aids at all for the Tina team, mine too breaks beyond **v0.66.9** upon clicking "Save" after making a change I would get the following

```
[
  TypeError: Cannot read properties of undefined (reading 'name')
      at Database.put (..\node_modules\@tinacms\graphql\dist\index.js:23643:34)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Resolver.updateResolveDocument (..\node_modules\@tinacms\graphql\dist\index.js:22633:7)
      at async fieldResolver (..\node_modules\@tinacms\graphql\dist\index.js:23228:37)
      at async Object.resolve (..\node_modules\@tinacms\graphql\dist\index.js:23112:17)
      at async ..\node_modules\@tinacms\cli\dist\index.js:95:24 {
    locations: [ [Object] ],
    path: [ 'updatePagesDocument' ]
  }
]
```

Also thank you @coreyaus for opening this, I was stuck trying to find out what I had broken and you just saved me a heck of a lot of time.

**Comment by cjmcintyre** [comment]
> @cjmcintyre I think the issue you are seeing may be fixed by #2815 - can you try this version of @tinacms/cli and let me know if that error is still occurring: [0.0.0-2022320142047](https://www.npmjs.com/package/@tinacms/cli/v/0.0.0-2022320142047)

Hi @kldavis4!
Your patch seems to address the issue of saving, however I found when I open my page in prior versions it would load the correct sidebar for that page (showing the components) now it seems to be opening the global sidebar and then requiring me to return to the form list and then find the correct page so I think we still may have an issue somewhere..

Packages as follows:
"@tinacms/cli": "0.0.0-2022320142047",
"tinacms": "0.67.1",

**Comment by kldavis4** [comment]
Ok, the patch for your issue has now been released. 

@jeffsee55 what's the fix for the global docs issue?

**Comment by jeffsee55** [comment]
@cjmcintyre if you're using the `formifyCallback` you'll need to update the id (this was a breaking change in 0.67 https://github.com/tinacms/tinacms/blob/main/packages/tinacms/CHANGELOG.md#minor-changes.

**Comment by cjmcintyre** [comment]
Cheers @jeffsee55, @kldavis4 seems to be working after changing the **formConfig.id** check from `getGlobalDocument` to `content\\global\\index.json`

**Comment by jeffsee55** [comment]
Thanks for the detailed report!

**Comment by jeffsee55** [comment]
> Collections break if they implement multiple different templates

@coreyaus can you run the audit command and let us know if that shows you any issues?

```
yarn tinacms audit
```

**Comment by coreyaus** [comment]
Thanks Jeff - that command doesn't find any issues - here's the full output:
```
Welcome to tina audit 🦙
Checking collection theme
Checking document: /Users/Corey/GitHub/sitejoy/content/theme/colours.json
Checking document: /Users/Corey/GitHub/sitejoy/content/theme/settings.json
Checking collection pages
Checking document: /Users/Corey/GitHub/sitejoy/content/pages/example.md
Checking document: /Users/Corey/GitHub/sitejoy/content/pages/inicio.md
Checking document: /Users/Corey/GitHub/sitejoy/content/pages/test.md
Checking collection tags
Checking document: /Users/Corey/GitHub/sitejoy/content/tags/climatechange.md
Checking document: /Users/Corey/GitHub/sitejoy/content/tags/humanrights.md
✅ Audit passed
✨  Done in 10.04s.
```
