### ISSUE TITLE
Links nested within "**" or "_" are giving the error: 'Not sure, this should be flattened to the same node'

### ISSUE THREAD

**Issue by the-digital-anarchist** [tinacms/tinacms#2884]
## Description

It seems not possible to have links in bold or italic texts.

I.e:

`_Quis semper vulputate [aliquam](https://link.com) venenatdis egestas sagittis quisque orci._`
or
`**Quis semper vulputate [aliquam](https://link.com) venenatdis egestas sagittis quisque orci.**`

Give the error message:

```
Warning: There was an error when fetching data
Error: Unable to fetch, errors: 
        Not sure, this should be flattened to the same node
    at LocalClient.request (/Users/augurk/projects/sandbox/tina-cloud-starter/node_modules/tinacms/dist/index.js:2273:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async requester1 (webpack-internal:///./.tina/__generated__/types.ts:376:16)
    at async getStaticProps (webpack-internal:///./pages/posts.tsx:59:23)
    at async Object.renderToHTML (/Users/augurk/projects/sandbox/tina-cloud-starter/node_modules/next/dist/server/render.js:387:20)
    at async doRender (/Users/augurk/projects/sandbox/tina-cloud-starter/node_modules/next/dist/server/next-server.js:1428:38)
    at async /Users/augurk/projects/sandbox/tina-cloud-starter/node_modules/next/dist/server/next-server.js:1523:28
    at async /Users/augurk/projects/sandbox/tina-cloud-starter/node_modules/next/dist/server/response-cache.js:63:36
error - pages/posts.tsx (10:42) @ HomePage
```

### Steps to reproduce

You can test it with the Tina cloud starter repo.

Go to a post and try to make a couple words with a link in it bold or italic in the rich text WYSIWYG. You will get the error when you try to save it.

### Expected result

What should happen?

It's valid markdown, so it should just get parsed.

#### Tinacms Package Versions

latest

closes https://linear.app/tina/issue/ENG-115

**Comment by jamespohalloran** [comment]
Can confirm I'm seeing the same thing on `"tinacms": "^0.68.4",` (current latest).

The issue seems to be when using a link within a bolded or italicized string.

**Comment by gitsstewart** [comment]
Note: if needs more definition/explanation from Jeff, hold another sprint

**Comment by jeffsee55** [comment]
Moving to blocked, see PR for explanation https://github.com/tinacms/tinacms/pull/2964
