### ISSUE TITLE
Error building GraphQL for collections with multiple templates (missing inline fragment)

### ISSUE THREAD

**Issue by coreyaus** [tinacms/tinacms#2904]
## Description

There are errors building the auto-generated GraphQL in projects that have collections with multiple templates after upgrading to the latest versions of the `tinacms` packages (**see example project to recreate the issue below**)

Specifically the queries generated to retrieve a document from such collections appear to be missing an inline fragment, related to this point: https://github.com/tinacms/tinacms/pull/2823#discussion_r856462237

> ... for collections with `templates` now you can't do something like this:
> 
> ```graphql
> # assume `post` has 2 templates, `blogPost` and `blockPost`
> post(relativePath: $relativePath) {
>   id
> }
> ```
> 
> `id` is available, but only when disambiguating. Since both `blogPost` and `blockPost` implement the `Document` interface, we can get pretty close to the same behavior:
> 
> ```graphql
> {
>   post(relativePath: $relativePath) {
>     ...on Document {
>       id
>     }
>   }
> }
> ```

### Steps to reproduce

You can see this issue by upgrading to the latest versions of `tinacms` and `@tinacms/cli` then trying to run `yarn dev` for any `tinacms` project that has collections with multiple templates. **I just created an example repository where you can see this issue: https://github.com/coreyaus/tinacms-issue-2904**. The process I followed was:

1. Create a new tina project using `npx create-tina-app@latest`, selecting Yarn with the Tailwind Starter
2. Updating the `schema.ts` so the blog posts collection implements 2 templates (rather than just a single set of fields) - this was the only code change I made and is visible in this commit: https://github.com/coreyaus/tinacms-issue-2904/commit/e31f5625b76345e8294be147b5464c8baa38dfab
3. Run `yarn dev` and review the error output (please see the full list of errors pasted below)

### Expected result

When running `yarn dev` the auto-generated GraphQL and types should be created/updated without errors.

### Actual result

At the moment there are errors with the latest versions of the `tinacms` packages in projects that have collections with multiple templates.

### Tinacms Package Versions

```text
├── @tinacms/auth@0.50.2
├── @tinacms/cli@0.60.15
├── next-tinacms-cloudinary@3.5.11
├── tinacms@0.68.2
```

I also tried with the following versions, which still show the same errors (see output below):

```text
├── @tinacms/auth@0.50.2
├── @tinacms/cli@0.60.16
├── next-tinacms-cloudinary@3.5.21
├── tinacms@0.68.4
```

### Error output

```text
AggregateError: GraphQL Document Validation failed with 9 errors;
  Error 0: GraphQLDocumentError: Cannot query field "id" on type "Post". Did you mean to use an inline fragment on "Document", "Node", "PostTemplate1", or "PostTemplate2"?
    at /Users/Corey/tinacms-issue-2904/.tina/queries/queries.gql:6:9

Error 1: GraphQLDocumentError: Cannot query field "_values" on type "Post". Did you mean to use an inline fragment on "Document", "PostTemplate1", or "PostTemplate2"?
    at /Users/Corey/tinacms-issue-2904/.tina/queries/queries.gql:7:9

Error 2: GraphQLDocumentError: Cannot query field "author" on type "Post". Did you mean to use an inline fragment on "PostTemplate1" or "PostTemplate2"?
    at /Users/Corey/tinacms-issue-2904/.tina/queries/queries.gql:8:9

Error 3: GraphQLDocumentError: Cannot query field "_sys" on type "Post". Did you mean to use an inline fragment on "Document", "PostTemplate1", or "PostTemplate2"?
    at /Users/Corey/tinacms-issue-2904/.tina/queries/queries.gql:13:9

Error 4: GraphQLDocumentError: Cannot query field "author" on type "Post". Did you mean to use an inline fragment on "PostTemplate1" or "PostTemplate2"?
    at /Users/Corey/tinacms-issue-2904/.tina/queries/queries.gql:32:5

Error 5: GraphQLDocumentError: Cannot query field "_sys" on type "Post". Did you mean to use an inline fragment on "Document", "PostTemplate1", or "PostTemplate2"?
    at /Users/Corey/tinacms-issue-2904/.tina/__generated__/queries.gql:3:5

Error 6: GraphQLDocumentError: Cannot query field "id" on type "Post". Did you mean to use an inline fragment on "Document", "Node", "PostTemplate1", or "PostTemplate2"?
    at /Users/Corey/tinacms-issue-2904/.tina/__generated__/queries.gql:11:5

Error 7: GraphQLDocumentError: Cannot query field "id" on type "Post". Did you mean to use an inline fragment on "Document", "Node", "PostTemplate1", or "PostTemplate2"?
    at /Users/Corey/tinacms-issue-2904/.tina/__generated__/queries.gql:21:9

Error 8: GraphQLDocumentError: Cannot query field "_sys" on type "Post". Did you mean to use an inline fragment on "Document", "PostTemplate1", or "PostTemplate2"?
    at /Users/Corey/tinacms-issue-2904/.tina/__generated__/queries.gql:22:9
    at Object.checkValidationErrors (/Users/Corey/tinacms-issue-2904/node_modules/@graphql-tools/utils/index.js:1253:15)
    at codegen (/Users/Corey/tinacms-issue-2904/node_modules/@graphql-codegen/core/index.js:153:15)
    at async generateTypes (/Users/Corey/tinacms-issue-2904/node_modules/@tinacms/cli/dist/index.js:322:17)
    at async genTypes (/Users/Corey/tinacms-issue-2904/node_modules/@tinacms/cli/dist/index.js:362:27)
    at async build2 (/Users/Corey/tinacms-issue-2904/node_modules/@tinacms/cli/dist/index.js:1595:7)
    at async FSWatcher.<anonymous> (/Users/Corey/tinacms-issue-2904/node_modules/@tinacms/cli/dist/index.js:1619:11)
	Typescript types => /Users/Corey/tinacms-issue-2904/.tina/__generated__/types.ts
	GraphQL types ====> /Users/Corey/tinacms-issue-2904/.tina/__generated__/schema.gql
```

**Comment by coreyaus** [comment]
In case it's helpful I've just checked and this still occurs in the latest package versions released today:

```text
├── @tinacms/auth@0.50.2
├── @tinacms/cli@0.60.17
├── next-tinacms-cloudinary@3.5.22
├── tinacms@0.68.5
```

**Comment by jamespohalloran** [comment]
Hey @coreyaus! What happens if you add `_template: "template1"` to your content? I got a different error when making the following request:

```
query MyQuery {
  post(relativePath: "voteForPedro.mdx") {
    ...on Document {
      id
    }
  }
}
```

But the request in http://localhost:4001/altair worked correctly for me once I added the `_template` line to your content

**Comment by logan-anderson** [comment]
@coreyaus It looks like the error output from the terminal when running `tinacms server:start` is causes from out autogenerated client not handling templates. If you want a temporary fix (Until the bug is fixed ) you can disable the generation of the client by using `yarn tinacms server:start --noSDK -c ...`

**Comment by coreyaus** [comment]
Thanks team!

@jamespohalloran - I pushed a commit to the example repository that adds the `_template: "template1"` property to both of the existing posts (and also upgrades to the latest Tina packages) but I'm still seeing the same errors: https://github.com/coreyaus/tinacms-issue-2904/commit/af6b41b2636b8042c316c9bfade460bee1d128a9

@logan-anderson - that's interesting to know. I can see that `--noSDK` flag allows the `yarn dev` command to succeed and build the auto-generated types. I'm guessing this would mean we couldn't use the `ExperimentalGetTinaClient` though, right? That's probably a bit of a deal breaker for this particular (non-urgent) project as we're using the `.tina/queries` system to generate a few custom queries we need. Your team are always quick on the pulse so I should be able to hold off for a fix on this one 😄 

Thanks again gents, and let me know anything I can do to help!

**Comment by coreyaus** [comment]
Thanks @logan-anderson!

I really appreciate the speedy work investigating and resolving that, plus I learned a bunch reading your updates on #2921 👌

I've been able to update my site to the latest patch versions of `tinacms` and `@tinacms/cli` so I can confirm your fix resolves the issue and allows the graphQL queries to build correctly for collections with templates 🎉  I've also updated the packages in use on the tinacms starter repo that reproduced the original issue (see this commit: https://github.com/coreyaus/tinacms-issue-2904/commit/503dcd7c382cc4b94016104bf2204cf213a2550d)

Now the site builds as expected there are an additional couple of issues that are now visible. Sorry to be responding to a bug fix with another bug report - hopefully the details are useful though, and it's definitely a massive win to have the sites and queries all building as expected now 🙏   The two issues below relate to the form generation process:

1. The graphQL queries now all build correctly, but **the forms don't actually appear for collections with multiple templates**. For example:
    - if you run [this starter repo](https://github.com/coreyaus/tinacms-issue-2904) locally and open a blog post in edit mode you'll see that no form appears in the sidebar: http://localhost:3000/post/anotherPost. While the blog post query executes correctly, it doesn't build a form as expected. This issue only exists for collections that implement templates, rather than static fields. For example, a global form still appears for the theme collection (which uses fields, not templates) - you can see the `content/global/index.json` link in the extra admin overlay / secondary sidebar.
    - Additionally, the `formConfig` for the blog post is still registered and visible in the `console.log` statements I added to the `formifyCallback` here: https://github.com/coreyaus/tinacms-issue-2904/blob/503dcd7c382cc4b94016104bf2204cf213a2550d/.tina/schema.ts#L408-L417. **So the form data is built, but for whatever reason the call to `createForm` doesn't actually build a form as expected for the blog post (or any other collection that implements templates)**
    - Happily the forms in the Tina admin interface still work for collections with multiple templates - it's just the contextual editing where those fail to appear at the moment.

2. Additionally, calling `return skip()` within the `formifyCallback` now throws the following error:
    > TypeError: Cannot read properties of undefined (reading 'id')
    - That error is raised by `buildFormNode` within `findFormNodes`
    - Obviously this is less problematic (the form I would be skipping is not building anyway now, given the issue explained in point 1)

Should I open a new issue with the details of these two bugs, or are you happy to simply reopen this issue? They're definitely less of a barrier than the original issue as the site still builds successfully. They mean contextual editing doesn't work at all for collections with multiple templates at the moment, but at least documents in those collections can still be created/edited through Tina Admin.

**Massive thanks for all your help with fixes so far - and definitely let me know anything I can do to help!** I took a look at the `tinacms` repository and could patch the second issue with a couple of conditionals but it wouldn't be very ergonomic (and might cause other issues). I haven't looked into the main `createForm` issue in point 1 but could try to take a look next weekend - not sure I'd be much help though to be honest!

**Comment by logan-anderson** [comment]
@coreyaus If you could put them into new issues that would be a big help (Makes it easier on our end for tracking and such). Feel free to tag me in them as well. 

Thanks for reporting these, it helps make the tina better. 

Thanks again 😄

**Comment by coreyaus** [comment]
Thanks @logan-anderson - I've just added those bug reports in #2929 and #2930 👍 Hope those details are helpful!
