### ISSUE TITLE
@tinacms/cli versions above 0.60.21 no longer work on Linux / Windows 

### ISSUE THREAD

**Issue by perkinsjr** [tinacms/tinacms#2996]
## Description

A user reported after upgrading above 0.60.21 their system throws an error when they are attempting to launch their localhost. Example error:

```
(node:17935) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use node --trace-deprecation ... to show where the warning was created)
node:fs:585
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/home/jperkins/GitHub/online-profile-nextjs/.tina/generated/_schema.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at FilesystemStore.get (/home/jperkins/GitHub/online-profile-nextjs/node_modules/@tinacms/datalayer/dist/index.js:235:53)
    at Database.getTinaSchema (/home/jperkins/GitHub/online-profile-nextjs/node_modules/@tinacms/graphql/dist/index.js:23749:25)
    at Database.getSchema (/home/jperkins/GitHub/online-profile-nextjs/node_modules/@tinacms/graphql/dist/index.js:23755:33)
    at Object.gqlServer (/home/jperkins/GitHub/online-profile-nextjs/node_modules/@tinacms/cli/dist/index.js:347:31)
    at start (/home/jperkins/GitHub/online-profile-nextjs/node_modules/@tinacms/cli/dist/index.js:1966:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/jperkins/GitHub/online-profile-nextjs/generated/_schema.json'
}
```

I have also confirmed the behavior with my working project (https://github.com/perkinsjr/james-perkins-dev) once you upgrade. The __generated__  folder becomes empty except for the `types.ts` which has the empty `export const queries` 

### Steps to reproduce

On a Linux or Windows machine:

1. Update to 0.60.22 or 0.60.23 
2.  run tina project
3. __generated__ will be empty

**Comment by elhe26** [comment]
I can confirm. I'm having the same issues.

**Comment by Zax337** [comment]
Same here. Reverted to 0.60.21 for now.
@elhe26 Can confirm it should work for you, I'm using the same versions as you do and it works (at least on Linux), maybe you should clean up your environment first.
