### ISSUE TITLE
Cannot query field on build

### ISSUE THREAD

**Issue by mmorkt** [tinacms/tinacms#3388]
## Description

First time using TinaCMS and i love it! But I'm getting a query error on build. Dev works fine, seems related to 
https://github.com/tinacms/tinacms/discussions/2249 and https://github.com/tinacms/tinacms/issues/3150.

I'm using the same fields and templates multiple times.

### Steps to reproduce

```
import { defineConfig, RouteMappingPlugin } from "tinacms";
import { client } from "./__generated__/client";
import { hero } from "./schema/hero";
import { text } from "./schema/text";
import { intro } from "./schema/intro";
import { cases } from "./schema/cases";

// globals
const builder = {
  name: "builder",
  label: "Builder",
  type: "object",
  list: true,
  templates: [text, hero, cases, intro],
};

const meta = {
  name: "meta",
  label: "Meta",
  type: "string",
  ui: {
    component: "textarea",
  },
};

const title = {
  name: "title",
  label: "Title",
  type: "string",
};

const image = {
  label: "image",
  name: "image",
  type: "image",
};

const config = defineConfig({
  client,
  clientId: process.env.NEXT_PUBLIC_TINA_CLIENT_ID,
  branch:
    process.env.NEXT_PUBLIC_TINA_BRANCH ||
    process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_REF ||
    process.env.HEAD,
  token: process.env.TINA_TOKEN,
  build: {
    publicFolder: "public",
    outputFolder: "admin",
  },
  media: {
    tina: {
      mediaRoot: "uploads",
      publicFolder: "public",
    },
  },
  schema: {
    collections: [
      {
        label: "Pages",
        name: "page",
        path: "content/page",
        format: "mdx",
        fields: [title, meta, builder],
      },
      {
        label: "Cases",
        name: "case",
        path: "content/case",
        format: "mdx",
        fields: [title, meta, image, builder],
      },
      {
        label: "Blog",
        name: "post",
        path: "content/post",
        format: "mdx",
        fields: [title, meta, image, builder],
      },
      {
        label: "Global",
        name: "global",
        path: "content/global",
        format: "json",
        ui: { global: true },
        fields: [
          {
            type: "string",
            label: "Site",
            name: "site",
          },
          {
            type: "object",
            label: "Menu",
            name: "menu",
            list: true,
            ui: {
              itemProps: (item) => {
                return { label: item?.name };
              },
            },
            fields: [
              {
                type: "string",
                label: "Name",
                name: "name",
              },
              {
                type: "string",
                label: "Url",
                name: "url",
              },
            ],
          },
        ],
      },
    ],
  },
.......

```

Example on component hero.js: 
```
export const hero = {
  label: "Hero",
  name: "hero",
  type: "object",
  fields: [
    {
      label: "Text",
      name: "text",
      type: "rich-text",
    },
    {
      label: "image",
      name: "image",
      type: "image",
    },
  ],
};

```

### Expected result

The build should pass with no errors.

### Actual result

```
Done building static site
Checking clientId, token and branch. ✅
Checking indexing process in Tina Cloud... ✅
info  - Loaded env from /Users/mortenmork-pedersen/sites/bend-web/.env
info  - Linting and checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data ...Error: Unable to fetch, please see our FAQ for more information: https://tina.io/docs/errors/faq/
  
        Errors: 
        Cannot query field "image" on type "Post".
Cannot query field "count" on type "PostBuilderCases".
Unknown type "PostBuilderIntro". Did you mean "PostBuilderHero", "PostBuilderFilter", "PostBuilder", "PostBuilderCases", or "PostBuilderText"?
    at TinaClient.request (/Users/mortenmork-pedersen/sites/bend-web/node_modules/tinacms/dist/client.js:71:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async requester (/Users/mortenmork-pedersen/sites/bend-web/.next/server/chunks/734.js:359:22)
    at async getStaticPaths (/Users/mortenmork-pedersen/sites/bend-web/.next/server/pages/blog/[slug].js:44:23)
    at async buildStaticPaths (/Users/mortenmork-pedersen/sites/bend-web/node_modules/next/dist/build/utils.js:594:33)
    at async /Users/mortenmork-pedersen/sites/bend-web/node_modules/next/dist/build/utils.js:925:115
    at async Span.traceAsyncFn (/Users/mortenmork-pedersen/sites/bend-web/node_modules/next/dist/trace/trace.js:79:20)

> Build error occurred
Error: Failed to collect page data for /blog/[slug]
    at /Users/mortenmork-pedersen/sites/bend-web/node_modules/next/dist/build/utils.js:955:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'Error'
}
info  - Collecting page data .%     
``` 

#### Tinacms Package Versions

```
── @tinacms/cli@0.62.3
── tinacms@0.70.2
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser | FF 108.0a1        |
| os      | macOS 12.6        |
| node    | 16.3.0        |
| npm     | 8.3.0        |

**Comment by mmorkt** [comment]
Did some more testing yesterday. By removing fields `title` and `image` plus changing some field types in the template components the build passed. 

Removed:
```
const title = {
  name: "title",
  label: "Title",
  type: "string",
};

const image = {
  label: "image",
  name: "image",
  type: "image",
};
```

**Comment by jamespohalloran** [comment]
Kind of seems like this might be a regression on https://github.com/tinacms/tinacms/pull/3033/files, maybe? @jeffsee55 @logan-anderson

**Comment by logan-anderson** [comment]
@mmorkt taking a look at this know. This might be a strange thing to try but can you try changing.

```js
const title = {
  name: "title",
  label: "Title",
  type: "string",
};
```

to 

```js 
const title =  () => {
  name: "title",
  label: "Title",
  type: "string",
};
```
and then instead of doing `title` you could do `title()`. 

This might be a workaround until we have a better fix.

**Comment by mmorkt** [comment]
Thank you @logan-anderson but got the same error running this function:

```
const title = () => {
  const data = {
    name: "title",
    label: "Title",
    type: "string",
  };
  return data;
};
```

**Comment by logan-anderson** [comment]
@mmorkt Thanks for trying, is your repo public by any chance? or if it's not is there anyway you could make a (small) demo that demonstrates this bug. I am having a hard time reproducing it with the information provided. 

Thanks in advance

**Comment by logan-anderson** [comment]
> Yup, you can find it her https://github.com/mgns-agency/bend-web

I was able to deploy it with no issues. I am also not seeing this issue locally.

https://www.loom.com/share/32c05df946e04bf9a0895f4c52638732

Is there something I am missing @mmorkt? Are you still seeing the error?

**Comment by mmorkt** [comment]
You are right  @logan-anderson! Removed the node_modules folder and reinstalled everything and now it works. Thanks for looking into this. Looking forward to be using TinaCMS.

**Comment by jamespohalloran** [comment]
Great to hear it's working! Does it work with your original schema? Or do you also need to apply @logan-anderson 's suggestion? https://github.com/tinacms/tinacms/issues/3388#issuecomment-1317228680

Just wondering if there's still a bug to sort out

**Comment by mmorkt** [comment]
@jamespohalloran the old schema works 🎉
