### ISSUE TITLE
TypeError - res.status is not a function

### ISSUE THREAD

**Issue by axelthat** [tinacms/tinacms#3502]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I am trying to get s3 working. This is my `netlify/functions/s3/s3.js`:

```
const express = require('express')
const bodyParser = require('body-parser')
const { isAuthorized } = require('@tinacms/auth')
const { createMediaHandler } = require('next-tinacms-s3/dist/handlers')

const app = express()
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())

const router = express.Router()

const handler = createMediaHandler({
  config: {
    credentials: {
      accessKeyId: process.env.NEXT_PUBLIC_S3_ACCESS_KEY || '',
      secretAccessKey: process.env.S3_SECRET_KEY || ''
    },
    region: process.env.NEXT_PUBLIC_S3_REGION
  },
  bucket: process.env.NEXT_PUBLIC_S3_BUCKET || '',
  authorized: async (req, _res) => {
    try {
      if (process.env.NODE_ENV == 'development') {
        return true
      }

      const user = await isAuthorized(req)

      return user && user.verified
    } catch (e) {
      console.error(e)
      return false
    }
  }
})

router.get('/s3/media', handler)

router.post('/s3/media', handler)

router.delete('/s3/:media', (req, res) => {
  req.query.media = ['media', req.params.media]
  return handler(req, res)
})

app.use('/api/', router)

module.exports = { handler }
```

And `netlify.toml`,
```
[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/s3/:splat'
  status = 200
```

And now when I goto: `https://mywebsite/api/s3/media?limit=20&clientID=XXXX`, I get the following error:

```
Jan 9, 12:33:29 PM: 8c2dce9a ERROR  TypeError: Cannot read properties of undefined (reading 'clientID')
    at isAuthorized (/var/task/node_modules/@tinacms/auth/dist/index.js:32:32)
    at Object.authorized (/var/task/netlify/functions/s3/s3.js:27:26)
    at Runtime.handler (/var/task/node_modules/next-tinacms-s3/dist/handlers.js:48:39)
    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1089:29)
Jan 9, 12:33:29 PM: 8c2dce9a ERROR  Invoke Error 	{"errorType":"TypeError","errorMessage":"res.status is not a function","stack":["TypeError: res.status is not a function","    at Runtime.handler (/var/task/node_modules/next-tinacms-s3/dist/handlers.js:50:11)"]}
Jan 9, 12:33:29 PM: 8c2dce9a Duration: 5.80 ms	Memory Usage: 104 MB	Init Duration: 777.53 ms
```

### Reproduction

.

### System Info

```shell
System:
  OS: macOS 13.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 333.95 MB / 16.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 16.18.0 - /opt/homebrew/opt/node@16/bin/node
  Yarn: 1.22.19 - ~/upwork/nick/cashforcars.io/node_modules/.bin/yarn
  npm: 8.19.2 - /opt/homebrew/opt/node@16/bin/npm
Browsers:
  Chrome: 108.0.5359.124
  Firefox: 104.0.2
  Safari: 16.2
npmPackages:
  @tinacms/auth: ^1.0.2 => 1.0.2 
  @tinacms/cli: ^1.0.5 => 1.0.5 
  tinacms: ^1.1.2 => 1.1.2
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by axelthat** [comment]
Just needed to wrap express with `serverless-http` package.

```
import serverless from 'serverless-http'

// express stuff

export const handler = serverless(app)
```
