### ISSUE TITLE
Connection to leader lost

### ISSUE THREAD

**Issue by axelthat** [tinacms/tinacms#3620]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I'm trying to use tina in my nextjs site. While running `npm run dev`, I get the following error:
```
 TinaCMS  - Build Started

No format provided for collection(s) "post", defaulting to .md
Indexing local files ⠋Compilation failed with errors. Server has not been restarted. see error below 
 Connection to leader lost
/Users/axelthat/tests/n/node_modules/many-level/guest.js:194
      req.callback(new ModuleError(msg, { code }))
                   ^

ModuleError: Connection to leader lost
    at TinaLevelClient.[abortRequests] (/Users/axelthat/tests/n/node_modules/many-level/guest.js:194:20)
    at Duplexify.cleanup (/Users/axelthat/tests/n/node_modules/many-level/guest.js:120:29)
    at Duplexify.<anonymous> (/Users/axelthat/tests/n/node_modules/readable-stream/lib/ours/util.js:43:16)
    at Duplexify.onerror (/Users/axelthat/tests/n/node_modules/readable-stream/lib/internal/streams/end-of-stream.js:103:14)
    at Duplexify.emit (node:events:525:35)
    at emitErrorNT (/Users/axelthat/tests/n/node_modules/readable-stream/lib/internal/streams/destroy.js:126:8)
    at emitErrorCloseNT (/Users/axelthat/tests/n/node_modules/readable-stream/lib/internal/streams/destroy.js:98:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'LEVEL_CONNECTION_LOST'
}
```

### Reproduction

https://github.com/axelthat/next-tina-bug

### Steps to reproduce

`npm i && npm run dev`

### System Info

```shell
System:
  OS: macOS 13.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 261.05 MB / 16.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 16.18.0 - /opt/homebrew/opt/node@16/bin/node
  Yarn: 1.22.19 - ~/tests/n/node_modules/.bin/yarn
  npm: 8.19.2 - /opt/homebrew/opt/node@16/bin/npm
Browsers:
  Chrome: 110.0.5481.100
  Firefox: 104.0.2
  Safari: 16.2
npmPackages:
  @tinacms/cli: ^1.2.1 => 1.2.1 
  tinacms: ^1.2.1 => 1.2.1
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
@axelthat Do you have any other process running on port 9000 ?

**Comment by axelthat** [comment]
@logan-anderson Sorry for late response. Yes, php-fpm is running on 9000. How do I specify a different port for tinacms?
