### ISSUE TITLE
Port conflicts with php-fpm and --datalayer-port not working

### ISSUE THREAD

**Issue by MagicLegend** [tinacms/tinacms#3742]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I'm following the [Hugo guide](https://tina.io/docs/frameworks/hugo/) on your website. I have PHP-FPM installed and started, which uses port 9000 by default. Fine, but trying to push the datalayer port to another port results in an exception:

```
❯ npx tinacms dev --datalayer-port 4002 -v
Starting Tina Dev Server
Indexing local files ⠋Error occured during tinacms dev
ModuleError: Connection to leader lost
    at [abortRequests] (/Users/<user>/Documents/private/tina-issue/tina-issue/node_modules/many-level/guest.js:194:20)
    at Duplexify.cleanup (/Users/<user>/Documents/private/tina-issue/tina-issue/node_modules/many-level/guest.js:120:29)
    at Duplexify.<anonymous> (/Users/<user>/Documents/private/tina-issue/tina-issue/node_modules/readable-stream/lib/ours/util.js:43:16)
    at Duplexify.onerror (/Users/<user>/Documents/private/tina-issue/tina-issue/node_modules/readable-stream/lib/internal/streams/end-of-stream.js:103:14)
    at Duplexify.emit (node:events:525:35)
    at emitErrorNT (/Users/<user>/Documents/private/tina-issue/tina-issue/node_modules/readable-stream/lib/internal/streams/destroy.js:126:8)
    at emitErrorCloseNT (/Users/<user>/Documents/private/tina-issue/tina-issue/node_modules/readable-stream/lib/internal/streams/destroy.js:98:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'LEVEL_CONNECTION_LOST'
}
```

### Reproduction

https://github.com/tinacms/tina-hugo-starter

### Steps to reproduce

```
npx create-tina-app@latest
> Yarn
> tina-issue
> Hugo Starter
yarn upgrade
npx tinacms dev --datalayer-port 4002 -v
```

(Not including a repo since no custom code is needed)

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 114.94 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - ~/Documents/private/tina-issue/tina-issue/node_modules/.bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Firefox: 111.0.1
    Safari: 16.3
  npmPackages:
    @tinacms/cli: ^1.0.0 => 1.4.1
    tinacms: ^1.0.0 => 1.4.0
```
```


### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jeffsee55** [comment]
Looks like we missed a piece on this config, fix on it's way. Thanks for the report

**Comment by MagicLegend** [comment]
@jeffsee55 Glad to hear! Thanks for the fix!
