### ISSUE TITLE
Cannot destructure property 'collectionString' of '(intermediate value)' as it is null

### ISSUE THREAD

**Issue by merc1er** [tinacms/tinacms#3847]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Running `npx @tinacms/cli@latest init` results in the following error at the step `Would you like to migrate your Forestry templates?`:

```sh
Error occured during tinacms init
TypeError: Cannot destructure property 'collectionString' of '(intermediate value)' as it is null.
    at initStaticTina (/Users/merc1er/.npm/_npx/b34d1f235ac7f645/node_modules/@tinacms/cli/dist/index.js:3793:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InitCommand.execute (/Users/merc1er/.npm/_npx/b34d1f235ac7f645/node_modules/@tinacms/cli/dist/index.js:4244:5)
    at async InitCommand.validateAndExecute (/Users/merc1er/.npm/_npx/b34d1f235ac7f645/node_modules/clipanion/lib/advanced/Command.js:73:26)
    at async Cli.run (/Users/merc1er/.npm/_npx/b34d1f235ac7f645/node_modules/clipanion/lib/advanced/Cli.js:223:24)
    at async Cli.runExit (/Users/merc1er/.npm/_npx/b34d1f235ac7f645/node_modules/clipanion/lib/advanced/Cli.js:232:28)
```

Full traceback:

```sh
❯  npx @tinacms/cli@latest init
✔ What is your Tina Cloud Client ID? (Hit enter to skip and set up yourself later)
Don't have a Client ID? Create one here: https://app.tina.io/projects/new … 
✔ Choose your package manager › NPM
✔ What framework are you using? › Other (SSG frameworks like gatsby, etc.)
✔ Would you like to use Typescript for your Tina Configuration (Recommended)? … no
✔ Where are public assets stored? (default: "public")
Not sure what value to use? Refer to our "Frameworks" doc: https://tina.io/docs/integration/frameworks/#configuring-tina-with-each-framework … ./
Forestry.io configuration found.
✔ Would you like to migrate your Forestry templates?
Note: This migration will update some of your content to match tina.  Please save a backup of your content before doing this migration. (This can be done with git) … no
Error occured during tinacms init
TypeError: Cannot destructure property 'collectionString' of '(intermediate value)' as it is null.
    at initStaticTina (/Users/merc1er/.npm/_npx/b34d1f235ac7f645/node_modules/@tinacms/cli/dist/index.js:3793:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InitCommand.execute (/Users/merc1er/.npm/_npx/b34d1f235ac7f645/node_modules/@tinacms/cli/dist/index.js:4244:5)
    at async InitCommand.validateAndExecute (/Users/merc1er/.npm/_npx/b34d1f235ac7f645/node_modules/clipanion/lib/advanced/Command.js:73:26)
    at async Cli.run (/Users/merc1er/.npm/_npx/b34d1f235ac7f645/node_modules/clipanion/lib/advanced/Cli.js:223:24)
    at async Cli.runExit (/Users/merc1er/.npm/_npx/b34d1f235ac7f645/node_modules/clipanion/lib/advanced/Cli.js:232:28)
```

### Reproduction

https://github.com/bchinfo/bch.info

### Steps to reproduce

```
git clone https://github.com/bchinfo/bch.info
cd bch.info
npx @tinacms/cli@latest init
```

Then, answer:
- `✔ What is your Tina Cloud Client ID? (Hit enter to skip and set up yourself later)` -> skip
- `✔ Choose your package manager` › `NPM`
- `✔ What framework are you using?` › `Other (SSG frameworks like gatsby, etc.)`
- `✔ Would you like to use Typescript for your Tina Configuration (Recommended)?` … `no` (tested with both yes and no, same result)
- `✔ Where are public assets stored? (default: "public")` … `./`
- `✔ Would you like to migrate your Forestry templates?` ... `no`

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: arm64 Apple M1 Pro
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.9.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 9.6.5 - /opt/homebrew/bin/npm
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
@merc1er  It looks like your site does not have any forestry templates so unfortunately the migration tool may not be super useful. 

In any case, we should display a better error message and still do some basic migration when this happen.

**Comment by merc1er** [comment]
Thanks for the reply!

> @merc1er It looks like your site does not have any forestry templates

Right, which is why I selected "no" to the question "Would you like to migrate your Forestry templates?".

I'll try setting up a Tina project from scratch then 🙂

I also have another website with templates. I'll try migrating that one.
