### ISSUE TITLE
Delete not working in windows

### ISSUE THREAD

**Issue by kldavis4** [tinacms/tinacms#4018]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

```
GraphQLError [Object]: Unable to find record content/post/dasdfsdf.md
    at Database.get (C:\Users\kldav\Documents\projects\tinacms\packages\@tinacms\graphql\dist\index.js:5133:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Resolver.getDocumentOrDirectory (C:\Users\kldav\Documents\projects\tinacms\packages\@tinacms\graphql\dist\index.js:4347:23)
    at async C:\Users\kldav\Documents\projects\tinacms\packages\@tinacms\graphql\dist\index.js:5610:26
    at async sequential (C:\Users\kldav\Documents\projects\tinacms\packages\@tinacms\graphql\dist\index.js:76:18)
    at async Database.query (C:\Users\kldav\Documents\projects\tinacms\packages\@tinacms\graphql\dist\index.js:5608:16)
    at async Resolver.resolveCollectionConnection (C:\Users\kldav\Documents\projects\tinacms\packages\@tinacms\graphql\dist\index.js:4712:22)
    at async Promise.all (index 4)
    at async Promise.all (index 0)
    at async resolve (C:\Users\kldav\Documents\projects\tinacms\packages\@tinacms\graphql\dist\index.js:4878:17)
    at async C:\Users\kldav\Documents\projects\tinacms\packages\@tinacms\cli\dist\index.js:1217:26
Error querying file content/post/dasdfsdf.md from collection post. Please run "tinacms audit" or add the --verbose option  for more info

GraphQL request:8:11
8 |           documents(sort: $sort, after: $after, first: $limit, filter: $filter,
  |           ^
  | folder: $folder) @include(if: $includeDocuments) {
event - compiled client and server successfully in 30.4s (2133 modules)
```

To reproduce: 

### Reproduction

https://github.com/tinacms/tinacms

### Steps to reproduce

On Windows, run the basic-iframe starter in the monorepo. Create a new post. Delete the post.

### System Info

```shell
windows 10 home
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kldavis4** [comment]
First reported by OnionKaaa on discord: https://discord.com/channels/835168149439643678/1118877765949730956

**Comment by cod3blox** [comment]
Are there any plans to fix this? On windows this issue is still there. I came across this issue today. At first I thougt it may be my fault with something, but the llama-link example also throws this errors when deleting items.
