### ISSUE TITLE
Difficult to debug when missing field breaks the index

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#4200]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Reported in Discord: https://discord.com/channels/835168149439643678/1150099809924038799/1150099809924038799

When adding a search index, build failed with: 

```
Building search index ⠹Error occured during tinacms dev
TypeError: data[f.name].map is not a function
    at processDocumentForIndexing (/Users/ollebergkvist/Documents/dev/projects/godsent.gg/node_modules/@tinacms/search/dist/index.js:113:39)
    at /Users/ollebergkvist/Documents/dev/projects/godsent.gg/node_modules/@tinacms/search/dist/index.js:114:22
    at Array.map (<anonymous>)
    at processDocumentForIndexing (/Users/ollebergkvist/Documents/dev/projects/godsent.gg/node_modules/@tinacms/search/dist/index.js:113:39)
    at /Users/ollebergkvist/Documents/dev/projects/godsent.gg/node_modules/@tinacms/search/dist/index.js:192:11
    at async sequential (/Users/ollebergkvist/Documents/dev/projects/godsent.gg/node_modules/@tinacms/graphql/dist/index.js:78:18)
    at async /Users/ollebergkvist/Documents/dev/projects/godsent.gg/node_modules/@tinacms/search/dist/index.js:176:7
    at async /Users/ollebergkvist/Documents/dev/projects/godsent.gg/node_modules/@tinacms/graphql/dist/index.js:3402:5
    at async reducePromises (/Users/ollebergkvist/Documents/dev/projects/godsent.gg/node_modules/@tinacms/graphql/dist/index.js:72:18)
    at async reducePromises (/Users/ollebergkvist/Documents/dev/projects/godsent.gg/node_modules/@tinacms/graphql/dist/index.js:72:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Looks like this is due to a missing field in a document. We should log out the field that's missing, and the document

### Reproduction

.

### Steps to reproduce

- Add search index
- Remove required fields from a document?
- run build

### System Info

```shell
?
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kldavis4** [comment]
See #4201 for the actual issue

**Comment by kldavis4** [comment]
This shouldn't occur with #4201 fixed - not sure how to reproduce otherwise so closing for now.
