### ISSUE TITLE
Remix Starter has TypeScript errors with URLSearchParams

### ISSUE THREAD

**Issue by jwithington** [tinacms/tinacms#4378]
I was trying to run the remix starter, following the [steps in the docs](https://tina.io/docs/introduction/using-starter/), but due to TypeScript errrors, the main localhost page wouldn't load.

Error from the page:

```
ypeError: Value of "this" must be of type URLSearchParams
    at new NodeError (node:internal/errors:405:5)
    at Proxy.set (node:internal/url:572:13)
    at Proxy.<anonymous> (/Users/jwithy/tina-cms-test/my-tina-app/node_modules/@remix-run/web-fetch/src/headers.js:124:44)
    at createRemixHeaders (/Users/jwithy/tina-cms-test/my-tina-app/node_modules/@remix-run/express/dist/server.js:58:17)
    at createRemixRequest (/Users/jwithy/tina-cms-test/my-tina-app/node_modules/@remix-run/express/dist/server.js:73:14)
    at /Users/jwithy/tina-cms-test/my-tina-app/node_modules/@remix-run/express/dist/server.js:37:21
    at /Users/jwithy/tina-cms-test/my-tina-app/node_modules/@remix-run/serve/dist/index.js:48:7
    at Layer.handle [as handle_request] (/Users/jwithy/tina-cms-test/my-tina-app/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/jwithy/tina-cms-test/my-tina-app/node_modules/express/lib/router/route.js:144:13)
    at next (/Users/jwithy/tina-cms-test/my-tina-app/node_modules/express/lib/router/route.js:140:7)
```

<img width="1043" alt="image" src="https://github.com/tinacms/tinacms/assets/4213550/7f01693a-5f64-407f-bb22-166902a0a01d">

### Reproduction

https://github.com/tinacms/tina-hugo-starter

### Steps to reproduce

- run the `npx create-tina-app@latest` command
- use npm instead of yarn (I had different problems when I tried to use Yarn, probably due to macOS issues on my new-ish laptop)
- pick the remix starter
- cd into the right folder and use `npm run dev`

Note: I was using Arc browser (which is Chromium-based), though it's not listed below in system info.

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M2
    Memory: 869.48 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.6.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/tina-cms-test/my-tina-app/node_modules/.bin/yarn
    npm: 9.8.1 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 117.1.58.124
    Edge: 119.0.2151.72
    Safari: 16.5.2
  npmPackages:
    @tinacms/cli: ^1.5.30 => 1.5.30
    tinacms: ^1.5.21 => 1.5.21
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kldavis4** [comment]
looks like this issue: https://github.com/remix-run/remix/issues/6118
