### ISSUE TITLE
Cannot use "classic-level" lib as databaseAdapter. TinaCMS not resolving node-gyp-build files

### ISSUE THREAD

**Issue by alexcupertme** [tinacms/tinacms#4492]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Versions: https://pastebin.com/skUyH6x2

Framework: NextJS 13.5.4 , app & pages router

database.ts file: https://pastebin.com/7aBSWACr

Problem i'm struggling with:

When running tinacms build --datalayer-port 8000 && next build i recieve 

```bash
> tinacms build --datalayer-port 8000 && next build

Starting Tina build
Error: No native build was found for platform=linux arch=x64 runtime=node abi=108 uv=1 libc=glibc node=18.19.1
    loaded from: /tmp/1713199946233

    at load.resolve.load.path (/tmp/1713199946233/database.build.js:54106:13)
    at load (/tmp/1713199946233/database.build.js:54069:34)
    at node_modules/.pnpm/classic-level@1.4.1/node_modules/classic-level/binding.js (/tmp/1713199946233/database.build.js:54257:48)
    at __require (/tmp/1713199946233/database.build.js:9:50)
    at node_modules/.pnpm/classic-level@1.4.1/node_modules/classic-level/index.js (/tmp/1713199946233/database.build.js:54390:19)
    at __require (/tmp/1713199946233/database.build.js:9:50)
    at Object.<anonymous> (/tmp/1713199946233/database.build.js:109507:36)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)

```

So i debugged these build files, and find out that TinaCMS build creates external directory at /tmp + Date.now(), so node-gyp-build cannot reach native build files. 

To reproduce you can use default tina cloud starter with Tina Self hosted setup and use classic-level as database adapter

### Reproduction

https://github.com/alexcupertme/tina-classic-level-bug

### Steps to reproduce

1. Clone reproduction repo (i omitted some parts of my configuration but it doesnt affect bug)
2. npm install
3. npm run build

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 6800HS Creator Edition
    Memory: 3.61 GB / 13.50 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
    Yarn: 1.22.19 - ~/skyfort/codebase/research/tina-classic-level-bug/node_modules/.bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
    pnpm: 8.11.0 - /usr/bin/pnpm
  npmPackages:
    @tinacms/cli: ^1.5.34 => 1.5.34 
    tinacms: ^1.5.24 => 1.5.24
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by bojidar-bg** [comment]
Seems like it's still an issue today.
Looking around the codebase, I would guess it's coming from
https://github.com/tinacms/tinacms/blob/455a033104100ef627871606bd59b7c6b3d9d016/packages/%40tinacms/cli/src/next/config-manager.ts#L374-L390
(The `esbuild` command for loading the database file was introduced in 4dd264e9eabcca9837f9df0e260dcda63ea43ecf, CC @jeffsee55 )
Naturally, manually going to `node_modules/@tinacms/cli/dist/index.js`, searching for "loadDatabaseFile" and replacing the whole body of the that function with `return require(this.selfHostedDatabaseFilePath).default` does the trick and at least makes `tinacms build` work, but I would imagine that is not the best workaround in this case 😅

**Comment by enBonnet** [comment]
I'm not sure if this issue is related or I had something else:

```bash
❯ pnpm install
Lockfile is up to date, resolution step is skipped
Packages: +2101
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 2101, reused 2098, downloaded 0, added 0, done
node_modules/.pnpm/core-js@3.44.0/node_modules/core-js: Running postinstall script, done in 146ms
node_modules/.pnpm/bufferutil@4.0.9/node_modules/bufferutil: Running install script, failed in 162ms
.../node_modules/bufferutil install$ node-gyp-build
│ node:events:497
│       throw er; // Unhandled 'error' event
│       ^
│ Error: spawn node-gyp ENOENT
│     at ChildProcess._handle.onexit (node:internal/child_process:285:19)
│     at onErrorNT (node:internal/child_process:483:16)
│     at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
│ Emitted 'error' event on ChildProcess instance at:
│     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
│     at onErrorNT (node:internal/child_process:483:16)
│     at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
│   errno: -2,
│   code: 'ENOENT',
│   syscall: 'spawn node-gyp',
│   path: 'node-gyp',
│   spawnargs: [ 'rebuild' ]
│ }
│ Node.js v22.19.0
└─ Failed in 162ms at /home/enbonnet/projects/tina.io/node_modules/.pnpm/bufferutil@4.0.9/node_modules/bufferutil
node_modules/.pnpm/better-sqlite3@11.10.0/node_modules/better-sqlite3: Running install script...
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by bojidar-bg** [comment]
@enBonnet Seems like you have an unrelated issue with your `node-gyp` installation--likely not related to Tina at all.
The issue discussed here occurs when doing a `tinacms build`, while yours seems to break at a much earlier time, when installing packages.

**Comment by enBonnet** [comment]
Yes, you were right, @bojidar-bg I worked around it by installing `node-gyp` as a development dependency. I don't know why I'd need it.

**Comment by kulesy** [comment]
Closing — this has been labeled `wontfix` and open since April 2024. Part of backlog refinement.
