### ISSUE TITLE
Dependency Issues

### ISSUE THREAD

**Issue by mcpeapsUnterstrichHD** [tinacms/tinacms#4788]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I start the dev server but ran in to dependecy errors in vite with no way to fix
```bash
/opt/homebrew/bin/yarn run dev
yarn run v1.22.21
warning ../../package.json: No license field
$ tinacms dev -c "next dev --turbo"
Starting Tina Dev Server
Indexing local files ⠋
Building search index ⠙
│
○  Tina Dev Server is running... ──────────────────────────────────────────╮
│                                                                          │
│  🦙 Tina Config                                                          │
│     CMS:                <your-dev-server-url>/admin/index.html           │
│     API playground:     <your-dev-server-url>/admin/index.html#/graphql  │
│     API url:            http://localhost:4001/graphql                    │
│                                                                          │
│  🤖 Auto-generated files                                                 │
│     GraphQL Client:     tina/__generated__/client.ts                     │
│     Typescript Types:   tina/__generated__/types.ts                      │
│                                                                          │
│                                                                          │
├──────────────────────────────────────────────────────────────────────────╯
Starting subprocess: next dev --turbo
✘ [ERROR] Failed to resolve entry for package "fs". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-pre-bundle]

    node_modules/vite/node_modules/esbuild/lib/main.js:1373:21:
      1373 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///Users/mahd/DEV/comboom_punkt_sucht_app/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:28725:11)
    at resolvePackageEntry (file:///Users/mahd/DEV/comboom_punkt_sucht_app/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:28722:5)
    at tryNodeResolve (file:///Users/mahd/DEV/comboom_punkt_sucht_app/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:28453:20)
    at Context.resolveId (file:///Users/mahd/DEV/comboom_punkt_sucht_app/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:28212:28)
    at Object.resolveId (file:///Users/mahd/DEV/comboom_punkt_sucht_app/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:44276:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/mahd/DEV/comboom_punkt_sucht_app/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:65937:21
    at async file:///Users/mahd/DEV/comboom_punkt_sucht_app/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:39976:34
    at async requestCallbacks.on-resolve (/Users/mahd/DEV/comboom_punkt_sucht_app/node_modules/vite/node_modules/esbuild/lib/main.js:1373:22)
    at async handleRequest (/Users/mahd/DEV/comboom_punkt_sucht_app/node_modules/vite/node_modules/esbuild/lib/main.js:729:13)

  This error came from the "onResolve" callback registered here:

    node_modules/vite/node_modules/esbuild/lib/main.js:1292:20:
      1292 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/mahd/DEV/comboom_punkt_sucht_app/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:39956:19)
    at handlePlugins (/Users/mahd/DEV/comboom_punkt_sucht_app/node_modules/vite/node_modules/esbuild/lib/main.js:1292:21)
    at buildOrContextImpl (/Users/mahd/DEV/comboom_punkt_sucht_app/node_modules/vite/node_modules/esbuild/lib/main.js:978:5)
    at Object.buildOrContext (/Users/mahd/DEV/comboom_punkt_sucht_app/node_modules/vite/node_modules/esbuild/lib/main.js:786:5)
    at /Users/mahd/DEV/comboom_punkt_sucht_app/node_modules/vite/node_modules/esbuild/lib/main.js:2186:68
    at new Promise (<anonymous>)
    at Object.context (/Users/mahd/DEV/comboom_punkt_sucht_app/node_modules/vite/node_modules/esbuild/lib/main.js:2186:27)
    at Object.context (/Users/mahd/DEV/comboom_punkt_sucht_app/node_modules/vite/node_modules/esbuild/lib/main.js:2026:58)
    at prepareEsbuildOptimizerRun (file:///Users/mahd/DEV/comboom_punkt_sucht_app/node_modules/vite/dist/node/chunks/dep-41cf5ffd.js:46041:35)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/tinacms/dist/client.mjs:20:47:
      20 │       this.cache = NodeCache(cacheDir, require("fs"));
         ╵                                                ~~~~

  ▲ Next.js 15.0.0-rc.0 (turbo)
  - Local:        http://localhost:3000
  - Environments: .env.local
  - Experiments (use with caution):
    · ppr
    · turbo
    · reactCompiler

 ✓ Starting...
warning ../../package.json: No license field
 ✓ Ready in 1930ms
```

### Reproduction

https://github.com/comboomPunkTsucht/comboom.sucht-BLOG/tree/dev

### Steps to reproduce

yarn install
yarn dev

### System Info

System:
    OS: macOS 15.1
    CPU: (8) arm64 Apple M1
    Memory: 141.39 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: v20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - ~/node_modules/.bin/npm
    pnpm: 7.25.1 - /opt/homebrew/bin/pnpm
  Browsers:
    Brave Browser: 126.1.67.123
    Safari: 18.1
    Safari Technology Preview: 18.0
    x Google Chrome Dev: 130.0.6710.0
  npmPackages:
    @tinacms/cli: ^1.6.3 => 1.6.3 
    @tinacms/toolkit: ^1.7.13 => 1.7.13 
    tinacms: ^2.2.3 => 2.2.3 

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by JackDevAU** [comment]
✅ PR with a fix has been merged - https://github.com/tinacms/tinacms/pull/4803 

Fix is available in `tinacms` version **2.2.6** & `@tinacms/cli` version **1.6.6**
