### ISSUE TITLE
Error on demo-next package

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#717]
## Description

Error when launching the demo-next on master

### Steps to reproduce

```
git pull 
npm run bs && npm run build
cd packages/demo-next
npm run develop
```

### Expected result

No build error

### Actual result

```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (/Users/frank/tina/tinacms/packages/next-tinacms-json/node_modules/react/cjs/react.development.js:1590:13)
    at Object.useState (/Users/frank/tina/tinacms/packages/next-tinacms-json/node_modules/react/cjs/react.development.js:1618:20)
    at useJsonForm (/Users/frank/tina/tinacms/packages/next-tinacms-json/dist/next-tinacms-json.cjs.development.js:37:25)
    at useLocalJsonForm (/Users/frank/tina/tinacms/packages/next-tinacms-json/dist/next-tinacms-json.cjs.development.js:111:22)
    at InlineJsonForm (/Users/frank/tina/tinacms/packages/next-tinacms-json/dist/next-tinacms-json.cjs.development.js:189:27)
    at processChild (/Users/frank/tina/tinacms/node_modules/react-dom/cjs/react-dom-server.node.development.js:3204:14)
    at resolve (/Users/frank/tina/tinacms/node_modules/react-dom/cjs/react-dom-server.node.development.js:3124:5)
    at ReactDOMServerRenderer.render (/Users/frank/tina/tinacms/node_modules/react-dom/cjs/react-dom-server.node.development.js:3598:22)
    at ReactDOMServerRenderer.read (/Users/frank/tina/tinacms/node_modules/react-dom/cjs/react-dom-server.node.development.js:3536:29)
    at renderToString (/Users/frank/tina/tinacms/node_modules/react-dom/cjs/react-dom-server.node.development.js:4245:27)
    at render (/Users/frank/tina/tinacms/node_modules/next/dist/next-server/server/render.js:80:16)
    at Object.renderPage (/Users/frank/tina/tinacms/node_modules/next/dist/next-server/server/render.js:291:16)
    at /Users/frank/tina/tinacms/packages/demo-next/.next/server/static/development/pages/_document.js:4360:21
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/frank/tina/tinacms/packages/demo-next/.next/server/static/development/pages/_document.js:239:24)
    at _next (/Users/frank/tina/tinacms/packages/demo-next/.next/server/static/development/pages/_document.js:261:9)
```

#### Tinacms Package Versions

```text
nextjs-blog-starter@0.2.1 /Users/frank/tina/tinacms/packages/demo-next
├── UNMET DEPENDENCY @tinacms/api-git@0.5.3
├── UNMET DEPENDENCY @tinacms/git-client@0.4.1
├── UNMET DEPENDENCY next-tinacms-json@0.1.2
├── UNMET DEPENDENCY next-tinacms-markdown@0.1.0-canary.2441
├── UNMET DEPENDENCY tinacms@^0.12.1
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |  Safari 13.0.4 (15608.4.9.1.3)   |
| os      |   masOS 10.15.2    |
| node    | v12.4.1  |
| npm     |    6.13.4     |

**Comment by ncphillips** [comment]
Weird. That definitely sounds like a bootstrap error to me. Maybe the package versions are wrong?

**Comment by DirtyF** [comment]
Getting a different error after fixing some packages versions:

```
Cannot read property 'position' of undefined
TypeError: Cannot read property 'position' of undefined
    at new qr (/Users/frank/tina/tinacms/packages/tinacms/build/index.js:1:91262)
    at /Users/frank/tina/tinacms/packages/tinacms/build/index.js:1:94265
    at Object.useMemo (/Users/frank/tina/tinacms/node_modules/react-dom/cjs/react-dom-server.node.development.js:1380:19)
    at Object.useMemo (/Users/frank/tina/tinacms/node_modules/react/cjs/react.development.js:1643:21)
    at /Users/frank/tina/tinacms/packages/tinacms/build/index.js:1:94239
    at processChild (/Users/frank/tina/tinacms/node_modules/react-dom/cjs/react-dom-server.node.development.js:3204:14)
    at resolve (/Users/frank/tina/tinacms/node_modules/react-dom/cjs/react-dom-server.node.development.js:3124:5)
    at ReactDOMServerRenderer.render (/Users/frank/tina/tinacms/node_modules/react-dom/cjs/react-dom-server.node.development.js:3598:22)
    at ReactDOMServerRenderer.read (/Users/frank/tina/tinacms/node_modules/react-dom/cjs/react-dom-server.node.development.js:3536:29)
    at renderToString (/Users/frank/tina/tinacms/node_modules/react-dom/cjs/react-dom-server.node.development.js:4245:27)
    at render (/Users/frank/tina/tinacms/node_modules/next/dist/next-server/server/render.js:80:16)
    at Object.renderPage (/Users/frank/tina/tinacms/node_modules/next/dist/next-server/server/render.js:291:16)
    at Function.getInitialProps (/Users/frank/tina/tinacms/packages/demo-next/.next/server/static/development/pages/_document.js:485:19)
    at Object.loadGetInitialProps (/Users/frank/tina/tinacms/node_modules/next/dist/next-server/lib/utils.js:59:29)
    at Object.renderToHTML (/Users/frank/tina/tinacms/node_modules/next/dist/next-server/server/render.js:295:36)
    at runMicrotasks (<anonymous>)
```

**Comment by ncphillips** [comment]
I'm pretty sure this was fixed. If you run `npm run hard-reset` it should be good

**Comment by DirtyF** [comment]
Confirmed, NextJS demo is working fine now on master.
